sudo: false
dist: trusty

language: node_js

node_js:
  - 10
  - 12
  - 14

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm release
      node_js: "14"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "krzysztof.furtak@gmail.com"
        api_key: $NPM_TOKEN
        gem: travis-kk-react-pagination
        on: deploy-npm-release